FinalExpense/Models/Charts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalExpense.Models
{
    public class Charts
    {
        public String X { get; set; }
        public int Y { get; set; }

    }
}

FinalExpense/Models/ChartsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalExpense.Models
{
    public class ChartsViewModel
    {
        public IEnumerable<Charts> ColumnChartPoints;
        public IEnumerable<Charts> PieChartPoints;
        public IEnumerable<Charts> LineChartPoints;
    }
}

FinalExpense/Models/ErrorViewModel.cs
using System;

namespace FinalExpense.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinalExpense/Models/Records.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalExpense.Models
{
    public class Records
    {
        public Guid Id { get; set; }
        public DateTime Date { get; set; }
        public string SalesRep { get; set; }
        public string Status { get; set; }
    }
}

FinalExpense/Models/RecordsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalExpense.Models
{
    public class RecordsViewModel
    {
        public Records[] Transfers { get; set; }
    }
}

FinalExpense/Controllers/CsvImportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FinalExpense.Services;
using FinalExpense.Models;
using Microsoft.AspNetCore.Http;

namespace FinalExpense.Controllers
{
    [Route("[controller]")]
    public class CsvImportController : Controller
    {
        private readonly CsvService _csvService;
        private readonly IRecordsService _RecordService;

        
        public CsvImportController(CsvService csvService, IRecordsService RecordService)
        {
            _csvService = csvService;
            _RecordService = RecordService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormFile csvFile)
        {
            
            if (csvFile != null && csvFile.Length > 0)
            {
                using (var stream = csvFile.OpenReadStream())
                {
                    try
                    {
                        ViewData["Message"] = _csvService.errorMessage;
                        var recordList = _csvService.ReadCsvFile(stream).ToList();
                        await _RecordService.AddRecordsAsync(recordList);
                        
                        return View(recordList); // Return users list to the view
                    }
                    catch (ApplicationException ex)
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                        ViewData["Message"] = ex.Message;
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError(string.Empty, $"An unexpected error occurred: {ex.Message}");
                        ViewData["Message"] = ex.InnerException.Message;
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Please select a valid CSV file.");
                ViewData["Message"] = "Please select a valid CSV file.";
            }
            return View();
        }
    }
}

FinalExpense/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FinalExpense.Models;
using FinalExpense.Services;
using Microsoft.AspNetCore.Http;

namespace FinalExpense.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRecordsService _RecordService;
        private readonly ChartService _chartService;

        public HomeController(ILogger<HomeController> logger, IRecordsService RecordsService, ChartService chartService)
        {
            _logger = logger;
            _RecordService = RecordsService;
            _chartService = chartService;
        }

        
        public IActionResult Index()
        {
            ChartsViewModel Points = new ChartsViewModel();

            Points.ColumnChartPoints = _chartService.GetColumnChart();
            Points.PieChartPoints = _chartService.GePieChart();
            Points.LineChartPoints = _chartService.GeLineChart();

            return View(Points);
           
        }

        public async Task<IActionResult> Records()
        {
            var records = await _RecordService.GetRecordsAsync();

            var model = new RecordsViewModel()
            {
                Transfers = records
            };

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalExpense/Views/CsvImport/Index.cshtml
@model IEnumerable<Records>

@{
    ViewData["Title"] = "CSV Records";
}

<h1>Upload CSV File</h1>
<form asp-controller="CsvImport" asp-action="Index" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <input type="file" name="csvFile" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Load</button>
</form>

@ViewData["Message"]

@if (Model != null)
{

    @*<p>@Html.DisplayFor(model => model.FirstOrDefault().Message)</p>*@

    <h1>CSV Records</h1>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SalesRep)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>

                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SalesRep)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>

                </tr>
            }

        </tbody>

    </table>
}

FinalExpense/Views/Home/Index.cshtml
@model ChartsViewModel;
@using Newtonsoft.Json;

<script src="~/js/canvasjs.min.js"></script>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

</div>

<div id="lineChart" style="width: 90%; height: 300px;display: inline-block;"></div><br />
<div id="columnChart" style="width: 45%; height: 300px;display: inline-block;"></div>
<div id="pieChart" style="width: 45%; height: 300px;display: inline-block;" ></div>

<script type="text/javascript">

    // result = JSON.parse('Html.Raw(JsonConvert.SerializeObject(Model.DataPoints))');
    // var result = Html.Raw(JsonConvert.SerializeObject(Model.DataPoints));
    var Cresult = @Html.Raw(Json.Serialize(Model.ColumnChartPoints));

    var columnPoints = [];
    for (var i = 0; i < Cresult.length; i++) {
        columnPoints.push({ label: Cresult[i].x, y: Cresult[i].y });
    }

    var Presult = @Html.Raw(Json.Serialize(Model.PieChartPoints));

    var piePoints = [];
    for (var i = 0; i < Presult.length; i++) {
        piePoints.push({ label: Presult[i].x, y: Presult[i].y });
    }

    var Lresult = @Html.Raw(Json.Serialize(Model.LineChartPoints));

    var linePoints = [];
    for (var i = 0; i < Lresult.length; i++) {
        linePoints.push({ label: Lresult[i].x, y: Lresult[i].y });
    }

    window.onload = function () {
        var columnchart = new CanvasJS.Chart("columnChart", {
            theme: "light1",
            animationEnabled: true,
            title: {
                text: "Employee Activity"
            },
            subtitles: [
                { text: "Total Transfers by Employee" }
            ],
            data: [
                {
                    type: "column", //change type to bar, line, area, pie, etc
                    dataPoints: columnPoints
                }
            ]
        });

        var pieChart = new CanvasJS.Chart("pieChart", {
            theme: "light1",
            title :{
	        text: "Billable Ratio"
            },
            data: [{
	        type: "pie",
	        dataPoints : piePoints
            }]
        });

         var lineChart = new CanvasJS.Chart("lineChart", {
            theme: "light1",
            title :{
	        text: "Transfers by Date"
            },
            data: [{
	        type: "line",
                dataPoints: linePoints
            }]
         });

        columnchart.render();
        pieChart.render();
        lineChart.render();
    };
</script>

FinalExpense/Views/Home/Records.cshtml
@* @model IEnumerable<FinalExpense.Models.RecordsViewModel>*@
@model RecordsViewModel

@{
    ViewData["Title"] = "Records";
}

<h1>Records</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Transfers.FirstOrDefault().Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transfers.FirstOrDefault().SalesRep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transfers.FirstOrDefault().Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Transfers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SalesRep)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

FinalExpense/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalExpense</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalExpense</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Records">Records</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CsvImport" asp-action="Index">Upload Records</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinalExpense - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>